ディレクトリを見やすく整形
yossuli/hackathon-vol14 pull request #60
Opened 2024-12-08 07:41 UTC by s-renren

### こんな感じになりました
![image](https://github.com/user-attachments/assets/0a55553d-be6e-4eed-9fb0-6c23b4683671)

2024-12-09 02:01 UTC, yossuli requested changes

2024-12-09 02:01 UTC, yossuli commented on client/pages/hanabi_creator/hanabi_creator.page.tsx
上に同じく

2024-12-09 02:01 UTC, yossuli commented on client/pages/hanabi_list/hanabi_list.module.css
上に同じく

2024-12-09 02:01 UTC, yossuli commented on client/pages/hanabi_list/hanabi_list.page.tsx
上に同じく

2024-12-09 04:50 UTC, Sho0226 commented
> ### こんな感じになりました
> ![image](https://private-user-images.githubusercontent.com/136290544/393578207-0a55553d-be6e-4eed-9fb0-6c23b4683671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MTk5NjgsIm5iZiI6MTczMzcxOTY2OCwicGF0aCI6Ii8xMzYyOTA1NDQvMzkzNTc4MjA3LTBhNTU1NTNkLWJlNmUtNGVlZC05ZmIwLTZjMjNiNDY4MzY3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwNDQ3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWQ3NTg1ZmQyN2U1NzQ2NDI5ZDUwMTljNjhhYjlkYTYwODdjMGIxNWE2MDQ4ZTA1MzhhYzUzMTQxOWJmMjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BophORlcArJRWp4aK-3G1nqBuPfH16M7KzOn3Bg5vCA)

2024-12-09 04:51 UTC, Sho0226 commented
↑ミスった
キャメルケースかスネークケース？統一してもいいかなとか

2024-12-10 05:56 UTC, s-renren commented
「上に同じく」しか見れなくてどこ指摘されてるかわからないからもう一回書いてくれませんか

2024-12-10 06:30 UTC, s-renren commented
本当にごめんなさい

2024-12-10 16:58 UTC, yossuli approved these changes
LGTM

2024-12-10 16:58 UTC, merged